name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . -t null_jobs_backend:latest

      - name: Save Docker image as tar
        if: success()
        run: docker save null_jobs_backend:latest > .tar


      - name: Check if everything is in place
        run: 
          echo ${{ secrets.SERVER_HOST }}
          echo ${{ secrets.SERVER_USERNAME }}
          echo ${{ secrets.SERVER_SSH_KEY }}
          ls | grep *.tar

      - name: Transfer Docker image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: null_jobs_backend_latest.tar
          target: /tmp/null_jobs_backend_latest.tar

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker load -i /tmp/null_jobs_backend_latest.tar
            sudo docker stop null_jobs_backend || true
            sudo docker rm null_jobs_backend || true
            sudo docker run -d --name null_jobs_backend -p 8080:8080 null_jobs_backend:latest

        
